---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-operator
  namespace: flux-system
spec:
  interval: 5m
  timeout: 1m
  retryInterval: 30s
  path: ./k8s/networking/cert-manager/operator
  force: true
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: flux-system
spec:
  interval: 5m
  timeout: 1m
  retryInterval: 30s
  path: ./k8s/networking/cert-manager/issuer
  dependsOn:
    - name: cert-manager-operator
  force: true
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
