keys:
  - &reonokiy age1ce4m2j28rx764twpcx672t8qq90uhshud8fft2pdyykltuggrygqccsp5t
  - &aios age1jkkntjuwmm856zxtju4qhk44n6vzsc79gmu804yajarggsymgusqfjcpjk
  - &buno age19xy4f5cljxcclae4rhm4ydx337trlfu9u9hadcak3expm4cc2y4sefpamp
creation_rules:
  - path_regex: secrets/aios.yaml
    key_groups:
      - age:
        - *reonokiy
        - *aios
  - path_regex: secrets/buno.yaml
    key_groups:
      - age:
        - *reonokiy
        - *buno
