---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/gimlet-io/capacitor-manifests
  ref:
    semver: "0.4.8" # https://github.com/Masterminds/semver
