---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-database
spec:
  interval: 10m
  chart:
    spec:
      chart: postgres-operator
      version: 1.14.0
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-charts
        namespace: flux-system
