---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: others
spec:
  interval: 10m
  chart:
    spec:
      chart: kyverno
      version: 3.3.4
      sourceRef:
        kind: HelmRepository
        name: kyverno-charts
        namespace: flux-system
