---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cyverno
  namespace: others
spec:
  interval: 10m
  chart:
    spec:
      chart: cyverno
      version: 1.13.2
      sourceRef:
        kind: HelmRepository
        name: cyverno-charts
        namespace: flux-system
