---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgres-operator-charts
  namespace: flux-system
spec:
  interval: 24h
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  timeout: 3m
