---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-operator
  namespace: traefik-networking
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 33.2.1
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
