---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - charts/cilium-charts.yaml
  - charts/coredns-charts.yaml
  - charts/hashicorp-charts.yaml
  - charts/jetstack-charts.yaml
  - charts/kube-vip-charts.yaml
  - charts/kyverno-charts.yaml
  - charts/longhorn-charts.yaml
  - charts/metrics-server-charts.yaml
  - charts/postgres-operator-charts.yaml
  - charts/postgres-operator-charts-ui.yaml
  - charts/tailscale-charts.yaml
  - charts/traefik-charts.yaml
