---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    networkPolicies:
      enable: true
      type: "rke2"
    persistence:
      defaultClass: true
      defaultFsType: ext4
      defaultDataLocality: best-effort
      migratable: true
