---
apiVersion: v1
kind: Namespace
metadata:
  name: networking
---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale-networking
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-networking
