---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale-networking
spec:
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.78.3
      sourceRef:
        kind: HelmRepository
        name: tailscale-charts
        namespace: flux-system
  values:
    oauth:
      clientId:
        secretKeyRef:
          name: tailscale-secrets
          key: client_id
      clientSecret:
        secretKeyRef:
          name: tailscale-secrets
          key: client_secret
