---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale-networking
spec:
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.78.3
      sourceRef:
        kind: HelmRepository
        name: tailscale-charts
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: tailscale-secrets
      valuesKey: clientId
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-secrets
      valuesKey: clientSecret
      targetPath: oauth.clientSecret
