---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 5m
  timeout: 1m
  retryInterval: 30s
  path: ./k8s/core
  dependsOn:
    - name: namespaces
    - name: sources
    - name: fix
    - name: secrets
  force: true
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
