---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 5m
  timeout: 1m
  retryInterval: 30s
  path: ./k8s/namespaces
  force: true
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
