---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 5m
  timeout: 1m
  retryInterval: 30s
  dependsOn:
    - name: flux-system
    - name: namespaces
    - name: sources
  path: ./k8s
  force: true
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: anso-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
