---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: anso-secrets
  namespace: flux-system
spec:
  interval: 5m
  url: ssh://git@github.com/reonokiy/anso-secrets.git
  ref:
    branch: main
  secretRef:
    name: flux-system
