---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: app-vault
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      version: 0.29.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp-charts
        namespace: flux-system

  values:
    global:
      enabled: true
      tlsDisable: false

    injector:
      enabled: true
      replicas: 3
      affinity: ""

      image:
        repository: "hashicorp/vault-k8s"
        tag: "1.6.1"

      agentImage:
        repository: "hashicorp/vault"
        tag: "1.18.3"

      agentDefaults:
        cpuLimit: "500m"
        cpuRequest: "250m"
        memLimit: "128Mi"
        memRequest: "64Mi"

      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 256Mi
          cpu: 250m

    server:
      enabled: true
      affinity: ""

      image:
        repository: "hashicorp/vault"
        tag: "1.18.3"

      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 512Mi
          cpu: 500m

      extraVolumes:
        - type: secret
          name: tls-ca
          path: /vault/userconfig/tls-ca
        - type: secret
          name: tls-server
          path: /vault/userconfig/tls-server

      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true
            cluster_name = "anso-vault"
            listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_cert_file = "/vault/userconfig/tls-server/tls.crt"
              tls_key_file = "/vault/userconfig/tls-server/tls.key"
            }

            storage "raft" {
              path = "/vault/data"
              retry_join {
                leader_api_addr = "https://vault-0.vault-internal:8200"
                leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
                leader_client_cert_file = "/vault/userconfig/tls-server/tls.crt"
                leader_client_key_file = "/vault/userconfig/tls-server/tls.key"
              }
              retry_join {
                leader_api_addr = "https://vault-1.vault-internal:8200"
                leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
                leader_client_cert_file = "/vault/userconfig/tls-server/tls.crt"
                leader_client_key_file = "/vault/userconfig/tls-server/tls.key"
              }
              retry_join {
                leader_api_addr = "https://vault-2.vault-internal:8200"
                leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
                leader_client_cert_file = "/vault/userconfig/tls-server/tls.crt"
                leader_client_key_file = "/vault/userconfig/tls-server/tls.key"
              }
            }

      readinessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
      livenessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true"
        initialDelaySeconds: 60

      dataStorage:
        enabled: true
        size: 1Gi
        mountPath: "/vault/data"
        storageClass: longhorn
      auditStorage:
        enabled: true
        size: 1Gi
        mountPath: "/vault/audit"
        storageClass: longhorn
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Retain

    ui:
      enabled: true
      serviceType: "ClusterIP"
      serviceNodePort: null
      externalPort: 8200
      serviceIPFamilyPolicy: "RequireDualStack"
